### PR TITLE
feat: enhance notes for event registrations

### PR DESCRIPTION
**Pull request by jonasmueller1**
add more detailed explanations which are necessarily to enter for event registrations due to many feedbacks from tour guides

@markocupic Thank you!

### CODE REVIEW

**Comment by markocupic** [comment]
@jonasmueller1: Thank you! Sorry for the delay! I'm a bit busy at the moment.

**Comment by jonasmueller1** [comment]
No problem. Take your time. It's not urgent at all. Just an improvement. Thanks.

This is not yet merged to master! No published changes...
Will you merge it manually?

**Comment by jonasmueller1** [comment]
Thank you!

Silly question: Have you already had the time to deploy it? 
I (still) don't see the text change on the live system... ;-)

Great weekend!

**Comment by jonasmueller1** [comment]
Ufff, the html tags are not supported:
Screenshot_20220522_095832_com android chrome~2

How can we fix that?

**Comment by markocupic** [comment]
> 

https://github.com/markocupic/sac-event-tool-bundle/commit/b98ce3815a2257becca26006e531fa8207db19c4

**Pull request merged**
