### PR TITLE
Feat/tour course template

### PR DESCRIPTION
**Pull request by jonasmueller1**
feat: group same topics together
feat: align template of tour and course
feat: add journey ("Anreise mit") in course template (which was missing)

@markocupic I tried to align the tour and the course template incl. ordering a little bit. It was hard for a better solution, but I tried my best ;-) Thank you for reviewing it!

Remark: This pull request is based on the https://github.com/markocupic/sac-event-tool-bundle/pull/18. Compare and merge this pull request after the https://github.com/markocupic/sac-event-tool-bundle/pull/18.

### CODE REVIEW

**Comment by markocupic** [comment]
@jonasmueller1: Let's test your improvements on the dev installation first. Ok?

**Comment by markocupic** [comment]
@jonasmueller1 

I like it! 👍 

image

**Comment by jonasmueller1** [comment]
Thank you!

Yes, sure, first on dev ;-)

Hmmm, that's still the old/current template of your tour screenshot... Now, you can compare it in detail ;-)

**Comment by jonasmueller1** [comment]
@markocupic That's the current/"old" template for courses:

CourseTemplate

**Comment by markocupic** [comment]
So, something went wrong

**Comment by markocupic** [comment]
Grr...

**Comment by jonasmueller1** [comment]
@markocupic For the courses, it works on dev env! 😄  This is the template with new changes:

CourseTemplateNew

PS: The previous picture was from prod env 😉

**Comment by jonasmueller1** [comment]
@markocupic And the new tour template on test env now 😉 
Now, we can compare it easily and improve if necessarily.

TourTemplateNew

**Comment by markocupic** [comment]
image

**Comment by jonasmueller1** [comment]
@markocupic Yes, I fully agree with you. The alignment/margin of the div box "Anmeldung" is not properly done by me... 

I hope, you agree with the alignment of the ordering from the tour and course template ;-)

**Comment by jonasmueller1** [comment]
Here are more (or almost all) fields entered for this course (just for comparison...):

CourseTemplateNew2

**Comment by jonasmueller1** [comment]
@markocupic Something like this?
```
<div class="row gx-5 ">
    <div class="col-md-12">
        <div class="m-0 pt-4 pb-2 bg-white">
            <div class="booking-text event-detail event-info-box icon-box-small">
                <h5>Anmeldung</h5>
            ...
```

grafik

**Comment by jonasmueller1** [comment]
@markocupic Thank you for your adaptations.

A remark:
I have the feeling that this in both templates doesn't work anymore (no change from my side):
`{% if not getEventData.invoke('journey') is empty and getEventData.invoke('journey') != 'not-specified' %}`

I see `Keine Angabe` for `Anreise mit` in the above picture.

**Comment by markocupic** [comment]
> I'm pretty amazed how well you do it.

**Comment by markocupic** [comment]
image

**Comment by markocupic** [comment]
So, I think it works.

**Comment by jonasmueller1** [comment]
👍 😃

**Pull request merged**
